### PR TITLE
3 macOS Menu Bar apps

### PR DESCRIPTION
**Pull request by kkarimz**
Added my personal 3 apps for mac os that are menuBar apps

### CODE REVIEW

**Comment by good** [comment]
These look like good additions! One small change I'd request for this PR is we try to order the apps alphabetically in each section, so would you mind placing the new additions in their correct spots? Thanks!

**Comment by kkarimz** [comment]
> These look like good additions! One small change I'd request for this PR is we try to order the apps alphabetically in each section, so would you mind placing the new additions in their correct spots? Thanks!

Thank you @good for your reply, and sorry I didn't notice this earlier. Fixed and ready for review again.

**Comment by kkarimz** [comment]
@good  just checking if you got a chance to review this. Thanks

**Comment by good** [comment]
Thanks! This looks great.

**Pull request merged**
